# Generated by Django 3.1.12 on 2025-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('aerodynamics', 'Aerodynamics'), ('aviation', 'Aviation'), ('personality-development', 'Personality Development'), ('soft-skills', 'Soft Skills'), ('corporate', 'Corporate'), ('industry', 'Industry Knowledge')], max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], max_length=50)),
                ('instructor_name', models.CharField(max_length=255)),
                ('instructor_pb_number', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='training_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
